/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;


import Control.NovedadesControl;
import Logica.NovedadesLogica;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexandra
 */
public class ConsultaNovedadesVista extends javax.swing.JPanel {
    int idtrabajador;
    /**
     * Creates new form ConsultaNovedadesVista
     */
    public ConsultaNovedadesVista(int idtrabajador) throws SQLException {
        initComponents();
        NovedadesControl nvC=new NovedadesControl();
        jTableNovedades.setModel(nvC.listaNovedades(idtrabajador));
        this.idtrabajador=idtrabajador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNovedades = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jBEliminar = new javax.swing.JButton();
        JBEditar = new javax.swing.JButton();

        jTableNovedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableNovedades);

        jLabel2.setText("Consultar Novedades de nomina");

        jBEliminar.setText("Eliminar Registro");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        JBEditar.setText("Editar Registro");
        JBEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(JBEditar)
                .addGap(32, 32, 32)
                .addComponent(jBEliminar)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar)
                    .addComponent(JBEditar))
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBEditarActionPerformed
        DefaultTableModel tm = (DefaultTableModel) jTableNovedades.getModel();
        int idNovedad= Integer.parseInt(String.valueOf(tm.getValueAt(jTableNovedades.getSelectedRow(),0)));
        int cantHoras= Integer.parseInt(String.valueOf(tm.getValueAt(jTableNovedades.getSelectedRow(),2)));
        NovedadesControl nvC=new NovedadesControl();
        try {
            nvC.editarNovedades(idNovedad, cantHoras);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaNovedadesVista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JBEditarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        System.out.println(jTableNovedades.getSelectedRow());
        DefaultTableModel tm = (DefaultTableModel) jTableNovedades.getModel();
        int idNovedad= Integer.parseInt(String.valueOf(tm.getValueAt(jTableNovedades.getSelectedRow(),0)));
        NovedadesControl nvC=new NovedadesControl();
        nvC.eliminarRegistro(idNovedad);
        try {
            jTableNovedades.setModel(nvC.listaNovedades(idtrabajador));
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaNovedadesVista.class.getName()).log(Level.SEVERE, null, ex);
        }
         JOptionPane.showMessageDialog(this, "Se eliminó el registro de forma exitosa");
    }//GEN-LAST:event_jBEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEditar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNovedades;
    // End of variables declaration//GEN-END:variables
}
