/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.NovedadesControl;
import Logica.NovedadesLogica;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandra
 */
public class JPanelRegistroNovedades extends javax.swing.JPanel {

    Vistas vistas = new Vistas();
    DateFormat df = new SimpleDateFormat("dd/MM/YYYY");
    private int idNovedad;
    private String idTraba;
    private boolean actualizar;

    public JPanelRegistroNovedades() throws SQLException {
        initComponents();
        NovedadesControl nvC = new NovedadesControl();
        for (int i = 0; i < nvC.tiposIncapacidad().size(); i++) {
            jCBoxTipoIncapacidad.addItem(nvC.tiposIncapacidad().get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFHoraED = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFHoraEN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFHoraENDOM = new javax.swing.JTextField();
        jTextFHoraEDDOM = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBGuardarHExtras = new javax.swing.JButton();
        jLTotalHoraExtras = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDateCHEDInicio = new com.toedter.calendar.JDateChooser();
        jDateCHENInicio = new com.toedter.calendar.JDateChooser();
        jDateCHEDDInicio = new com.toedter.calendar.JDateChooser();
        jDateCHENDInicio = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jPanelIncapacidad = new javax.swing.JPanel();
        jCBoxTipoIncapacidad = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jBGuardarIncapacidad = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jDateCInicioIncapacidad = new com.toedter.calendar.JDateChooser();
        jDateCLlegadaIncapacidad = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jDateClicenciaInicio = new com.toedter.calendar.JDateChooser();
        jDateCLicenciaFin = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jBGuardarILicencia = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserInicioRN = new com.toedter.calendar.JDateChooser();
        jDateChooserInicioRD = new com.toedter.calendar.JDateChooser();
        jButtonRecargoN = new javax.swing.JButton();
        jBRecargosDominical = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jDateChooserFinRN = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jDateChooserFinRD = new com.toedter.calendar.JDateChooser();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jBConsultarNovedades = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        JTFIDtrabajador = new javax.swing.JTextField();
        jBConsultarTrabajador = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculo horas extras"));

        jLabel1.setText("Hora extra Diurna");

        jLabel2.setText("Hora extra Nocturna");

        jLabel3.setText("Hora extra Dominical y/o festiva:");

        jLabel4.setText("6:00am - 9:00pm ");

        jTextFHoraED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFHoraEDActionPerformed(evt);
            }
        });
        jTextFHoraED.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFHoraEDKeyTyped(evt);
            }
        });

        jLabel5.setText("9:00pm - 6:00am ");

        jTextFHoraEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFHoraENActionPerformed(evt);
            }
        });
        jTextFHoraEN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFHoraENKeyTyped(evt);
            }
        });

        jLabel6.setText("Hora extra Diurna");

        jLabel7.setText("Hora extra Nocturna");

        jTextFHoraENDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFHoraENDOMActionPerformed(evt);
            }
        });
        jTextFHoraENDOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFHoraENDOMKeyTyped(evt);
            }
        });

        jTextFHoraEDDOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFHoraEDDOMActionPerformed(evt);
            }
        });
        jTextFHoraEDDOM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFHoraEDDOMKeyTyped(evt);
            }
        });

        jLabel8.setText(" 6:00am - 9:00pm ");

        jLabel9.setText("9:00pm - 6:00am ");

        jLabel10.setText("Hora extra días normales:");

        jBGuardarHExtras.setText("Cargar Horas Extras");
        jBGuardarHExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarHExtrasActionPerformed(evt);
            }
        });

        jLTotalHoraExtras.setText(" ");

        jLabel22.setText("Inicio");

        jLabel11.setText("Cantidad de horas extras entre: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFHoraEDDOM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFHoraENDOM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(83, 83, 83)
                                        .addComponent(jDateCHENDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDateCHEDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateCHENInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateCHEDDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 32, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLTotalHoraExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBGuardarHExtras)
                                .addGap(8, 8, 8))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFHoraEN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFHoraED, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel11))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFHoraED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateCHEDInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextFHoraEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jDateCHENInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFHoraEDDOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFHoraENDOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jDateCHEDDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateCHENDInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTotalHoraExtras)
                    .addComponent(jBGuardarHExtras))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelIncapacidad.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de incapacidad"));

        jCBoxTipoIncapacidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguna" }));

        jLabel12.setText("Seleccione el tipo de incapacidad");

        jBGuardarIncapacidad.setText("Cargar Incapacidad");
        jBGuardarIncapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarIncapacidadActionPerformed(evt);
            }
        });

        jLabel14.setText("Seleccione la fecha de inicio de incapacidad");

        jLabel25.setText("Seleccione la fecha en que el trabajador retomó tareas");

        javax.swing.GroupLayout jPanelIncapacidadLayout = new javax.swing.GroupLayout(jPanelIncapacidad);
        jPanelIncapacidad.setLayout(jPanelIncapacidadLayout);
        jPanelIncapacidadLayout.setHorizontalGroup(
            jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIncapacidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIncapacidadLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBoxTipoIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIncapacidadLayout.createSequentialGroup()
                        .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelIncapacidadLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanelIncapacidadLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)))
                        .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBGuardarIncapacidad)
                            .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jDateCInicioIncapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                .addComponent(jDateCLlegadaIncapacidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelIncapacidadLayout.setVerticalGroup(
            jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelIncapacidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBoxTipoIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(30, 30, 30)
                .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jDateCInicioIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelIncapacidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelIncapacidadLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelIncapacidadLayout.createSequentialGroup()
                        .addComponent(jDateCLlegadaIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardarIncapacidad)
                        .addGap(0, 11, Short.MAX_VALUE))))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Licencias no remuneradas"));

        jLabel26.setText("Inicio");

        jLabel27.setText("Fin");

        jBGuardarILicencia.setText("Cargar Licencia");
        jBGuardarILicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarILicenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateClicenciaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jBGuardarILicencia)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(194, 194, 194)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel27)
                                .addComponent(jDateCLicenciaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(69, 69, 69))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateCLicenciaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateClicenciaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jBGuardarILicencia)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Recargos "));

        jLabel15.setText("Recargo Nocturno");

        jLabel16.setText("Recargo Dominical o Festivo");

        jButtonRecargoN.setText("Agregar Recargo Nocturno");
        jButtonRecargoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecargoNActionPerformed(evt);
            }
        });

        jBRecargosDominical.setText("Agregar Recargo Dominical");
        jBRecargosDominical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRecargosDominicalActionPerformed(evt);
            }
        });

        jLabel21.setText("Jornada laboral entre: 9:00pm y 6:00am");

        jLabel28.setText("Inicio");

        jLabel29.setText("Fin");

        jLabel30.setText("Inicio");

        jLabel31.setText("Fin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBRecargosDominical)
                            .addComponent(jButtonRecargoN)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jDateChooserInicioRD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDateChooserFinRD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jDateChooserInicioRN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jDateChooserFinRN, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserInicioRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFinRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jButtonRecargoN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserInicioRD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jBRecargosDominical))
                    .addComponent(jDateChooserFinRD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(356, 356, 356))
        );

        jBConsultarNovedades.setText("Consultar Novedades");
        jBConsultarNovedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarNovedadesActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Novedades del Trabajador"));

        jLabel13.setText("Digite el numero de identificación del trabajador*");

        JTFIDtrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFIDtrabajadorActionPerformed(evt);
            }
        });
        JTFIDtrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTFIDtrabajadorKeyTyped(evt);
            }
        });

        jBConsultarTrabajador.setText("Consultar");
        jBConsultarTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarTrabajadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(29, 29, 29)
                .addComponent(JTFIDtrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBConsultarTrabajador)
                .addGap(0, 292, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(JTFIDtrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBConsultarTrabajador))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBConsultarNovedades)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 511, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelIncapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConsultarNovedades)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFHoraEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFHoraEDActionPerformed

    }//GEN-LAST:event_jTextFHoraEDActionPerformed

    private void jTextFHoraEDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFHoraEDKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFHoraEDKeyTyped

    private void jTextFHoraENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFHoraENActionPerformed

    }//GEN-LAST:event_jTextFHoraENActionPerformed

    private void jTextFHoraENKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFHoraENKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFHoraENKeyTyped

    private void jTextFHoraENDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFHoraENDOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFHoraENDOMActionPerformed

    private void jTextFHoraENDOMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFHoraENDOMKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFHoraENDOMKeyTyped

    private void jTextFHoraEDDOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFHoraEDDOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFHoraEDDOMActionPerformed

    private void jTextFHoraEDDOMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFHoraEDDOMKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFHoraEDDOMKeyTyped

    private void jBGuardarHExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarHExtrasActionPerformed
        int idtraba = 0;

        if (JTFIDtrabajador.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe digitar la identificación del trabajador");
        } else {
            NovedadesControl nl;
            idtraba = Integer.parseInt(JTFIDtrabajador.getText());
            int horas = Integer.parseInt((jTextFHoraED.getText().trim().isEmpty()) ? "0" : jTextFHoraED.getText());
            String fechaInicio = null;
            String fechaFin = null;

            if (horas != 0) {
                try {
                    fechaInicio = df.format(jDateCHEDInicio.getDate());
                    System.out.println("Fecha: " + jDateCHEDInicio.getDate());
                    fechaFin = df.format(jDateCHEDInicio.getDate());
                    System.out.println("FECHA: " + fechaInicio);
                    nl = new NovedadesControl(idtraba, "Hora extra Diurna", horas, fechaInicio, fechaFin);
                   JOptionPane.showMessageDialog(this, "Se guardó con éxito las horas extras");
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            horas = Integer.parseInt((jTextFHoraEN.getText().trim().isEmpty()) ? "0" : jTextFHoraEN.getText());
            if (horas != 0) {
                fechaInicio = df.format(jDateCHENInicio.getDate());

                fechaFin = df.format(jDateCHENInicio.getDate());
                try {
                    nl = new NovedadesControl(idtraba, "Hora extra Nocturna", horas, fechaInicio, fechaFin);
                    JOptionPane.showMessageDialog(this, "Se guardó con éxito las horas extras");
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            horas = Integer.parseInt((jTextFHoraEDDOM.getText().trim().isEmpty()) ? "0" : jTextFHoraEDDOM.getText());
            if (horas != 0) {
                fechaInicio = df.format(jDateCHEDDInicio.getDate());
                System.out.println("FECHA: " + fechaInicio);
                fechaFin = df.format(jDateCHEDDInicio.getDate());
                //df.format(jDateCHEDDInicio.getDate().getTime()+(86400000*7));
                System.out.println("Fecha chedd " + fechaFin);
                try {
                    nl = new NovedadesControl(idtraba, "Hora extra Dominical/F Diurna", horas, fechaInicio, fechaFin);
                    JOptionPane.showMessageDialog(this, "Se guardó con éxito las horas extras");
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            horas = Integer.parseInt((jTextFHoraENDOM.getText().trim().isEmpty()) ? "0" : jTextFHoraENDOM.getText());
            if (horas != 0) {
                //  1 Día = 86400000 Milisegundos
                fechaInicio = df.format(jDateCHENDInicio.getDate());
                fechaFin = df.format(jDateCHENDInicio.getDate());
                try {
                    nl = new NovedadesControl(idtraba, "Hora extra Dominical/F Nocturna", horas, fechaInicio, fechaFin);
                    JOptionPane.showMessageDialog(this, "Se guardó con éxito las horas extras");
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_jBGuardarHExtrasActionPerformed

    private void jButtonRecargoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecargoNActionPerformed
        int idtraba = 0;

        if (JTFIDtrabajador.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe digitar la identificación del trabajador");
        } else {
            idtraba = Integer.parseInt(JTFIDtrabajador.getText());
            if (jDateChooserInicioRN.getDate() != null && jDateChooserFinRN.getDate() != null) {
                int cantDias = Integer.parseInt(df.format(jDateCHEDDInicio.getDate().getTime() / (86400000 * 7)));
                try {
                    NovedadesControl nl = new NovedadesControl(idtraba, "Recargo Nocturno", cantDias,
                            df.format(jDateChooserInicioRN.getDate()), df.format(jDateChooserFinRN.getDate()));
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Se guardó con éxito las incapacidad");
            }
        }
    }//GEN-LAST:event_jButtonRecargoNActionPerformed

    private void jBRecargosDominicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRecargosDominicalActionPerformed
        int idtraba = 0;

        if (JTFIDtrabajador.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Debe digitar la identificación del trabajador");
        } else {
            idtraba = Integer.parseInt(JTFIDtrabajador.getText());
            if (jDateChooserInicioRD.getDate() != null && jDateChooserFinRD.getDate() != null) {
                int cantDias = (int) (jDateChooserFinRD.getDate().getTime()
                        - jDateChooserInicioRD.getDate().getTime()) / (86400000);
                try {
                    NovedadesControl nl = new NovedadesControl(idtraba, "Recargo Dominical o Festivo", cantDias,
                            df.format(jDateChooserInicioRD.getDate()), df.format(jDateChooserFinRD.getDate()));
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(this, "Se guardó con éxito las incapacidad");
            }
        }
    }//GEN-LAST:event_jBRecargosDominicalActionPerformed

    private void jBConsultarNovedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarNovedadesActionPerformed
        int continuar = JOptionPane.showConfirmDialog(this, "Si continua se borrará la información que no haya guardado"
                + "\n ¿Desea Continuar?");
        if (continuar == JOptionPane.YES_OPTION) {
            int idtraba = 0;

            if (JTFIDtrabajador.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Debe digitar la identificación del trabajador");
            } else {
                idtraba = Integer.parseInt(JTFIDtrabajador.getText());
                try {
                    EscritorioGestorNomina.esctiorioGestorNomina.add(vistas.returnInternal(new ConsultaNovedadesVista(idtraba), "Consulta de novedades"));
                    EscritorioGestorNomina.esctiorioGestorNomina.getSelectedFrame().dispose();
                    EscritorioGestorNomina.esctiorioGestorNomina.selectFrame(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

    }//GEN-LAST:event_jBConsultarNovedadesActionPerformed

    private void JTFIDtrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFIDtrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFIDtrabajadorActionPerformed

    private void jBConsultarTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarTrabajadorActionPerformed
        String idtrabajador = JTFIDtrabajador.getText();
        //Conectarlo a la clase que camilo haga de trabajador.
        boolean esValido = true;//Llamar metodo
        if (esValido) {

            /*  jPanelIncapacidad.setVisible(true);
            jPanel2.setVisible(true);
            jPanel3.setVisible(true);
            jPanel1.setVisible(true);
             */
        }

    }//GEN-LAST:event_jBConsultarTrabajadorActionPerformed

    private void jBGuardarIncapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarIncapacidadActionPerformed
        String itemSeleecionado = (String) jCBoxTipoIncapacidad.getSelectedItem();
        if (!JTFIDtrabajador.getText().trim().equals("")) {
            if (itemSeleecionado.equals("Ninguna")) {
                JOptionPane.showMessageDialog(this, "Debe rellenar los campos obligatorios para guardar una incapacidad");
            } else {
                int cantDias = (int) ((jDateCLlegadaIncapacidad.getDate().getTime()
                        - jDateCInicioIncapacidad.getDate().getTime()) / 86400000);
                if (cantDias > 0) {
                    int idtraba = Integer.parseInt(JTFIDtrabajador.getText());
                    String tipoIncapacidad = itemSeleecionado;
                    // System.out.println("item seleccionado: " + tipoIncapacidad);
                    try {

                        NovedadesControl nl = new NovedadesControl(idtraba, tipoIncapacidad, (cantDias * 8),
                                df.format(jDateCInicioIncapacidad.getDate()), df.format(jDateCLlegadaIncapacidad.getDate()));
                        JOptionPane.showMessageDialog(this, "Se guardó con éxito las incapacidad");
                    } catch (SQLException ex) {
                        Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "las fechas deben ser coherentes");
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe digitar la identificación del trabajador");
        }

    }//GEN-LAST:event_jBGuardarIncapacidadActionPerformed

    private void JTFIDtrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTFIDtrabajadorKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_JTFIDtrabajadorKeyTyped

    private void jBGuardarILicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarILicenciaActionPerformed
        String itemSeleecionado = (String) jCBoxTipoIncapacidad.getSelectedItem();
        if (!JTFIDtrabajador.getText().trim().equals("")) {
            if (jDateClicenciaInicio.getDate() != null && jDateCLicenciaFin.getDate() != null) {
                JOptionPane.showMessageDialog(this, "Debe rellenar los campos obligatorios para guardar una incapacidad");
            } else {
                int cantDias = (int) ((jDateCLicenciaFin.getDate().getTime()
                        - jDateClicenciaInicio.getDate().getTime()) / 86400000);
                if (cantDias > 0) {
                    int idtraba = Integer.parseInt(JTFIDtrabajador.getText());
                    String tipoIncapacidad = itemSeleecionado;
                    try {

                        NovedadesControl nl = new NovedadesControl(idtraba, tipoIncapacidad, (cantDias),
                                df.format(jDateClicenciaInicio.getDate()), df.format(jDateCLicenciaFin.getDate()));
                        JOptionPane.showMessageDialog(this, "Se guardó con éxito las incapacidad");
                    } catch (SQLException ex) {
                        Logger.getLogger(JPanelRegistroNovedades.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "las fechas deben ser coherentes");
                }

            }

        } else {
            JOptionPane.showMessageDialog(this, "Debe digitar la identificación del trabajador");
        }
    }//GEN-LAST:event_jBGuardarILicenciaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFIDtrabajador;
    private javax.swing.JButton jBConsultarNovedades;
    private javax.swing.JButton jBConsultarTrabajador;
    private javax.swing.JButton jBGuardarHExtras;
    private javax.swing.JButton jBGuardarILicencia;
    private javax.swing.JButton jBGuardarIncapacidad;
    private javax.swing.JButton jBRecargosDominical;
    private javax.swing.JButton jButtonRecargoN;
    private javax.swing.JComboBox<String> jCBoxTipoIncapacidad;
    private com.toedter.calendar.JDateChooser jDateCHEDDInicio;
    private com.toedter.calendar.JDateChooser jDateCHEDInicio;
    private com.toedter.calendar.JDateChooser jDateCHENDInicio;
    private com.toedter.calendar.JDateChooser jDateCHENInicio;
    private com.toedter.calendar.JDateChooser jDateCInicioIncapacidad;
    private com.toedter.calendar.JDateChooser jDateCLicenciaFin;
    private com.toedter.calendar.JDateChooser jDateCLlegadaIncapacidad;
    private com.toedter.calendar.JDateChooser jDateChooserFinRD;
    private com.toedter.calendar.JDateChooser jDateChooserFinRN;
    private com.toedter.calendar.JDateChooser jDateChooserInicioRD;
    private com.toedter.calendar.JDateChooser jDateChooserInicioRN;
    private com.toedter.calendar.JDateChooser jDateClicenciaInicio;
    private javax.swing.JLabel jLTotalHoraExtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelIncapacidad;
    private javax.swing.JTextField jTextFHoraED;
    private javax.swing.JTextField jTextFHoraEDDOM;
    private javax.swing.JTextField jTextFHoraEN;
    private javax.swing.JTextField jTextFHoraENDOM;
    // End of variables declaration//GEN-END:variables
}
